# Sử dụng một image Python chính thức làm base image
FROM python:3.10-slim

# Cài đặt các thư viện cần thiết
RUN apt-get update && \
    apt-get install -y \
    gcc \
    libffi-dev \
    libxml2-dev \
    libxslt1-dev \
    zlib1g-dev \
    libjpeg-dev \
    libpq-dev \
    build-essential \
    unixodbc \
    unixodbc-dev \
    && rm -rf /var/lib/apt/lists/*


# Tạo thư mục làm việc và đặt nó làm thư mục hiện tại
WORKDIR /app

# Sao chép các file cần thiết vào container
COPY requirements.txt requirements.txt
COPY . .

# Cài đặt các thư viện Python
RUN pip install --no-cache-dir -r requirements.txt

# Expose port nếu cần thiết (Ví dụ: port 80)
# EXPOSE 80

# Chạy ứng dụng Python
CMD ["python", "main3.py"]
#docker run -it -v D:\telebot\Output:/app/Output telebot:v1